### ISSUE TITLE
Write Code to Connect the Student Submission Form with the Student Form Table.

### ISSUE THREAD

**Issue by TeamBoykov** [TeamBoykov1/CoopReportingTool#39]
#7

**Comment by Alagu91** [comment]
Done with the coding for inserting data to the coopform table. But having error as data is not inserted in back-end. So will work on it in Iteration 2 and commit later. 1.5 points spent for this task so far.

**Comment by TeamBoykov** [comment]
Changes have been made to reflect Iteration 2 plan.
