### ISSUE TITLE
Write code to connect the stored procedures, student table and student list page.

### ISSUE THREAD

**Issue by TeamBoykov** [TeamBoykov1/CoopReportingTool#47]
#11

**Comment by srichatala** [comment]
Code has written on Student Report page connect with coopreport table to display all student coop reports , selected student coop reports (Advisor can filter by using studentID and month)  in a grid view. 
Committed Number: 57c2c4fcbe248e0d14507671f56ba8ea05344ac0

**Comment by TeamBoykov** [comment]
Changes have been made to reflect Iteration 2 plan.
