### ISSUE TITLE
Build HTML for Student Submission Form Page.

### ISSUE THREAD

**Issue by TeamBoykov** [TeamBoykov1/CoopReportingTool#8]
#7

**Comment by TeamBoykov** [comment]
Changes have been made to reflect Iteration 2 plan.

**Comment by sukhpreetsekhon** [comment]
Commit# 556b26ebc85a73f024b3d5636795adef88b13555
task #8
story point: 2.5
unfortunately i commit it through jasmeet's laptop due to some issues in my laptop and was unaware that it will not get committed like this.
